"""add_project_name_column

Revision ID: 64f72e17dc2d
Revises: 952656ac53ee
Create Date: 2026-02-06 21:27:54.666200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64f72e17dc2d'
down_revision: Union[str, None] = '952656ac53ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_name', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'projects', ['project_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='unique')
    op.drop_column('projects', 'project_name')
    # ### end Alembic commands ###
